services:
  winksia:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: winksia
    restart: always
    env_file:
      - .env
    ports:
      - 8020:5000
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    networks:
      - winksia
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 2G
        reservations:
          cpus: '1.00'
          memory: 1G

networks:
  winksia:
    driver: bridge